namespace VezCheckClean

module Checklists =

    let dailyChecklist = [
        "Primary cooling system pressure check"
        "Secondary cooling circuit temperature control"
        "Pump feedback signal verification"
        "UPS power supply status"
        "Main control panel LED indicators"
        "Alarm system test"
        "Control rod position feedback"
        "Heat exchanger inlet/outlet temperature"
        "Feedwater system pressure monitoring"
        "Diesel generator standby check"
        "Auto cooling fan operation test"
        "Hydraulic valve status lights"
        "Reactor zone temperature sensor readout"
        "Access door interlock system test"
        "Control console ventilation check"
        "Instrumentation grounding check"
        "Coolant loop circulation flow check"
        "Primary loop water chemistry sampling"
        "PLC module error light verification"
        "Reactor water level display check"
        "Annunciator light test"
        "Radiation badge reader status"
        "Emergency evacuation signage illumination"
        "Network status indicator check"
        "Operator shift log timestamp"
        "Daily SCADA connectivity check"
        "Reactor mode switch position verification"
        "Lighting intensity measurement in control room"
        "End-of-shift checklist handover"
        "Fire suppression system panel light check"
        "Redundant input power path validation"
        "Sensor readout verification on display units"
        "Operator presence acknowledgement sensor check"
        "Control terminal label integrity check"
        "Status light power cycling test"
        "Manual override key switch test"
        "Data logger sync confirmation"
        "Wall-mounted equipment inspection"
        "Floor safety marking review"
        "SCADA polling rate monitor"
    ]

    let weeklyChecklist = [
        "Diesel generator automatic test"
        "Mechanical testing of safety valves"
        "Backup power source activation test"
        "Emergency shutdown button test"
        "Simulated emergency stop procedure"
        "Radiation monitor diagnostics"
        "SCADA system data backup"
        "Manual control panel button testing"
        "Compressor system operational check"
        "Cooling water tank level verification"
        "Redundant system crossover functionality"
        "Reactor building pressure integrity test"
        "Airlock door mechanical seal inspection"
        "Electrical relay board test"
        "Motor control cabinet temperature check"
        "Fire extinguisher pressure gauge test"
        "Lighting panel functional check"
        "System log review and signoff"
        "Emergency radio test"
        "Physical key inventory check"
        "Uninterruptible power interface test"
        "Weekly mechanical vibration trend review"
        "Hot standby systems checklist"
        "Reactor water conductivity sampling"
        "Control rod step position logging"
        "Battery charger state-of-health test"
        "Ventilation duct sensor calibration"
        "Seismic sensor self-test"
        "Physical access panel status check"
        "Labeling and tagging compliance verification"
        "Training log verification"
        "Backup procedure binder audit"
        "Operations crew check-in verification"
    ]

    let monthlyChecklist = [
        "Calibration of radiation sensors"
        "Fire protection system full function test"
        "Load test of backup diesel generator"
        "Inspection of control system updates"
        "Pressure test of charging/discharging system"
        "UPS battery replacement or charge check"
        "Surveillance camera system test"
        "Fan vibration and noise level measurement"
        "Control console display brightness test"
        "Emergency lighting system full test"
        "HVAC filter replacement"
        "Battery room temperature logging"
        "Containment vessel seal inspection"
        "Backup SCADA node restart test"
        "Cable integrity test in high-voltage area"
        "Documentation revision verification"
        "Floor marking and safety signage check"
        "Instrumentation cabinet cleanliness check"
        "Critical spare parts availability check"
        "Long-term maintenance task scheduling"
        "Reactor floor decontamination procedure"
        "Fire door closure timer verification"
        "Pressure gauge calibration log check"
        "Monthly incident simulation drill log"
        "Radiation shielding panel visual check"
        "Hazardous area gas detector test"
        "Reactor safety case documentation signoff"
        "Dry run of quarterly emergency drill"
        "Test of satellite communication link"
        "Review of all active alarms"
        "Monthly operator skills review"
        "External inspection coordination checklist"
        "Temporary work permit audit"
    ]

    let getChecklist (checkListType: string) =
        match checkListType.ToLowerInvariant() with
        | "daily"   -> dailyChecklist
        | "weekly"  -> weeklyChecklist
        | "monthly" -> monthlyChecklist
        | _         -> []
